// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.44
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeMetricsViewer
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCodeMetricsViewerPackageString = "ea48a032-1e88-4fa6-a4d5-23ac705eba22";
        public static Guid guidCodeMetricsViewerPackage = new Guid(guidCodeMetricsViewerPackageString);

        public const string guidCodeMetricsViewerPackageCmdSetString = "3ee9e66f-96c3-4177-aff7-ada2c5773c8e";
        public static Guid guidCodeMetricsViewerPackageCmdSet = new Guid(guidCodeMetricsViewerPackageCmdSetString);

        public const string guidImagesString = "b07d1a21-bb80-4310-ae48-f25e81ec601b";
        public static Guid guidImages = new Guid(guidImagesString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolWindow1CommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}
